name = "Hippopotamus"
license = "MIT"
licenselink = "https://github.com/thatlittlegit/hugo-theme-hippopotamus/blob/master/LICENSE.md"
description = "Minimal theme with minimal CSS."
homepage = "https://github.com/thatlittlegit/hugo-theme-hippopotamus"
tags = ["blog"]
features = ["blog"]
min_version = "0.30.2"

[author]
  name = "thatlittlegit"
  homepage = "https://github.com/thatlittlegit/hugo-theme-hippopotamus"
